### ISSUE TITLE
Photo or link for the style board that works with this box

### ISSUE THREAD

**Issue by scgt1** [NIK4658/Podium-KillSwitch-Replica#1]
First time on this platform so probably doing this wrong @NIK4658 Is there a chance you can add a photo or link to the board that works with this box. There are several different styles, shapes, and sizes out there from looking on Amazon. 

It even seems something like this may work if it clips in the opening in the mounting base. https://www.amazon.com/gp/aw/d/B0BGN9LMCQ

**Comment by NIK4658** [comment]
Hi, for this project you don't necessarily need to have a board that splits the cables, you can simply cut the wire and split the wires inside it again following the diagram provided.

In any case, I tried to find the board I used for this project but unfortunately I couldn't find an image of the product I used, I found another one that is very similar anyway.

https://shorturl.at/yAQR1

Always remember to use the right input format for the electronic board, i.e. RJ12 (6P6C)

**Comment by scgt1** [comment]
With a bit more digging this may have been the one you used since it has the extra unused location https://www.amazon.com/Connector-Breakout-Board-Module-terminals/dp/B0BC172XGK/<https://www.amazon.com/Connector-Breakout-Board-Module-terminals/dp/B0BC172XGK/ref=sr_1_5?crid=3TW7ZAXLYS63A&keywords=RJ11+6P6C+Connector+Breakout+Board+Module&qid=1683069416&sprefix=rj11+6p6c+connector+breakout+board+module%2Caps%2C175&sr=8-5>

What exactly is the purpose of the half moon circle area that sticks up inside the box from the bottom base? Seems as if that would interfere with the buttons that are put in the top without seeing it in person anyway.

Is the square cut out in the bottom the standard size for a female connector or is it basically just a pass through opening to run a RJ12 phone line through?

If it's a standard size for the connector my initial thoughts of using the below connector and RJ12 Straight Wire diagram should work out where it can clip into the square and be secure. Didn't really want to have wires running inside and being prone to getting snagged and something rip loose inside the box with just snipping a RJ12 phone line and soldering direct. https://m.media-amazon.com/images/I/717dTPJz5NL._AC_SL1500_.jpg
[https://m.media-amazon.com/images/I/717dTPJz5NL._AC_SL1500_.jpg]


________________________________

**Comment by NIK4658** [comment]
Yes, the first photo you linked is basically what I used, but this has a green section that mine hasn't. Anyway that's optional and I think you can basically cut it out without issues.

The half moon you see isn't on the inside but on the outside, and It's used to mount the KillSwitch on the Rig using an M10 bolt and two nuts.

The square hole at the bottom is slightly smaller than the size of the metal female connector i used, the difference is minimal.
The dimensions of that square hole are 14x14x3 (mm).

You can use the simpler one you linked and just connect the right wires on it, it will work anyway. Just make sure you fix the connector with hot glue or super glue and respect the wiring diagram.

Hope I was helpful!

**Comment by scgt1** [comment]
Yes thank you very much.

________________________________

**Comment by NIK4658** [comment]
You're welcome!
